language: cpp

dist: focal

sudo: required

branches:
    only:
        - master

matrix:
    allow_failures:
         - os: osx

    include:
        - name: "Linux; gcc 9; debug"
          os: linux
          python: "3.8"
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++
          env:
              - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
              - TRAVIS_BUILD_TYPE=Debug
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
              - TRAVIS_PYTHON_VERSION=3.8
          #before_install:
              #- ./environment/travis/linux/before_install.sh
          install:
              - source environment/travis/linux/install.sh
          before_script:
              - ./environment/travis/linux/before_script.sh
          script:
              - ./environment/travis/script.sh


        - name: "Linux; gcc 10; release"
          os: linux
          python: "3.8"
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-10
          env:
              - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
              - TRAVIS_BUILD_TYPE=Release
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
              - TRAVIS_PYTHON_VERSION=3.8
          #before_install:
              #- ./environment/travis/linux/before_install.sh
          install:
              - source environment/travis/linux/install.sh
          before_script:
              - ./environment/travis/linux/before_script.sh
          script:
              - ./environment/travis/script.sh

        - name: "macOS; clang 11; release"
          os: osx
          osx_image: xcode9.4
          env:
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
          addons:
              homebrew:
                  packages:
                      - llvm
                      - qt5
                      - xerces-c
                      - ncurses
                      - boost
                      - gdal
          before_install:
              #- brew update
              #- brew install llvm@6
              #- brew install qt5 xerces-c ncurses
              ## Force the latest versions
              ## - brew outdated boost || brew upgrade boost
              ## - brew outdated gdal || brew upgrade gdal
              #- brew outdated cmake || brew upgrade cmake
              - cmake --version
              - pip3 install psutil
              - which python3
          before_script:
              - mkdir $TRAVIS_BUILD_DIR/build
              - cd $TRAVIS_BUILD_DIR/build
              - ls -al /usr/local/opt/
              - ls -al /usr/local/Cellar/
              - ls -al /opt
              - ls -al /usr/local/opt/ncurses/
              - export PATH="/usr/local/opt/qt/bin:$PATH"
              #- CC=/usr/local/opt/llvm@6/bin/clang CXX=/usr/local/opt/llvm@6/bin/clang++
              - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DPCRASTER_BUILD_TEST=ON -DPCRASTER_BUILD_TEST_FERN=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/ncurses -DCMAKE_RULE_MESSAGES=OFF ..
          script:
              - cd $TRAVIS_BUILD_DIR
              - pwd
              - ./environment/travis/script.sh



notifications:
    email:
        recipients:
            - k.dejong1@uu.nl
            - o.schmitz@uu.nl
        on_success: change
        on_failure: always
