language: cpp

dist: trusty

sudo: required

branches:
    only:
        - master

matrix:
    allow_failures:
         - os: osx

    include:
        - name: "Linux; gcc 4.9; debug"
          os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
          env:
              - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
              - TRAVIS_BUILD_TYPE=Debug
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
          before_install:
              - ./environment/travis/linux/before_install.sh
          install:
              - source environment/travis/linux/install.sh
          before_script:
              - ./environment/travis/linux/before_script.sh
          script:
              - ./environment/travis/script.sh


        - name: "Linux; gcc 8; release"
          os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
              - TRAVIS_BUILD_TYPE=Release
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
          before_install:
              - ./environment/travis/linux/before_install.sh
          install:
              - source environment/travis/linux/install.sh
          before_script:
              - ./environment/travis/linux/before_script.sh
          script:
              - ./environment/travis/script.sh

        - name: "macOS; clang 6; release"
          os: osx
          osx_image: xcode9.4
          env:
              - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
          before_install:
              - brew update
              - clang --version
              - clang++ --version
              - cmake --version
              - brew install llvm@6
              - clang --version
              - clang++ --version
              - brew install qt5 qwt xerces-c ncurses
              - brew install boost
              - brew install boost-python
              # Force the latest versions
              - brew outdated gdal || brew upgrade gdal
              - brew outdated cmake || brew upgrade cmake
              - cmake --version
          before_script:
              - mkdir $TRAVIS_BUILD_DIR/build
              - cd $TRAVIS_BUILD_DIR/build
              - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DFERN_BUILD_ALGORITHM:BOOL=TRUE -DPCRASTER_BUILD_TEST:BOOL=TRUE ..
          script:
              - ./environment/travis/script.sh



notifications:
    email:
        recipients:
            - k.dejong1@uu.nl
            - o.schmitz@uu.nl
        on_success: change
        on_failure: always
