name: Linux CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-20.04

        timeout-minutes: 120

        name: "Linux CI"

        steps:

        - name: Checkout PCRaster
          uses: actions/checkout@v2

        - name: Configure system
          run: |
              sudo apt update
              sudo apt install gcc-10 ninja-build gdal-bin libgdal-dev libxerces-c-dev libxml2-dev libxslt1-dev libboost-all-dev libncurses5-dev libxml2 libxml2-utils mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx python3 libpython3-dev python3-numpy python3-psutil qtbase5-dev libqt5charts5-dev libqt5opengl5-dev cmake pybind11-dev
              # Only required for documentation:
              sudo apt install python3-sphinx doxygen python3-matplotlib graphviz

        - name: Configure PCRaster
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G"Ninja Multi-Config" \
                  -D CMAKE_C_COMPILER=gcc-10 \
                  -D CMAKE_CXX_COMPILER=g++-10 \
                  -D PCRASTER_BUILD_TEST=ON \
                  -D PCRASTER_BUILD_DOCUMENTATION=ON \
                  -D CMAKE_CONFIGURATION_TYPES="Release;Debug" \
                  -D Python3_EXECUTABLE:FILEPATH=/usr/bin/python3 \
                  -D CMAKE_INSTALL_PREFIX=package

        - name: Build debug
          shell: bash
          run: |
              cmake --build build --config Debug --target all

        - name: Build release
          shell: bash
          run: |
              cmake --build build --config Release --target all

        - name: Install PCRaster
          shell: bash
          run: |
              cmake --install build --config Release

        - name: Create source package
          shell: bash
          run: |
              cmake --build build --config Release --target package_source

        - name: Test debug
          env:
              LOGNAME: pcrtester
          shell: bash
          run: |
              cd build
              ctest --output-on-failure --build-config Debug

        - name: Test release
          env:
              LOGNAME: pcrtester
          shell: bash
          run: |
              cd build
              ctest --output-on-failure --build-config Release
