name: macOS CI

on: [push]

jobs:
    build:

        runs-on: macos-latest

        name: "macOS CI"

        steps:

        - name: checkout pcraster
          uses: actions/checkout@v2

        - name: configure system
          run: |
              brew install cmake ninja boost gdal ncurses xerces-c qt@5
              pip3 install psutil

        - name: configure pcraster
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G "Ninja" \
                  -D CMAKE_RULE_MESSAGES=OFF \
                  -D PCRASTER_BUILD_TEST=ON \
                  -D PCRASTER_BUILD_TEST_FERN=ON \
                  -D CMAKE_PREFIX_PATH=/usr/local/opt/ncurses;/usr/local/opt/qt5

        - name: build
          shell: bash
          run: |
              # cmake --build build --config Debug --target all
              cmake --build build --config Release --target all

        - name: install
          shell: bash
          run: |
              cmake --install build --config Release --prefix package

        - name: source package
          shell: bash
          run: |
              cmake --build build --config Release --target package_source

        - name: test
          shell: bash
          run: |
              # cmake --build build --config Debug --target test
              cmake --build build --config Release --target test
              ctest -C build --rerun-failed --output-on-failure
