name: macOS CI

on: [push]

jobs:
    build:

        runs-on: macos-latest

        timeout-minutes: 120

        name: "macOS CI"

        steps:

        - name: checkout pcraster
          uses: actions/checkout@v2

        - name: configure system
          run: |
              brew install python@3.x cmake ninja boost gdal ncurses xerces-c psutils pybind11 qt@5

        - name: configure pcraster
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G "Ninja Multi-Config" \
                  -D PCRASTER_BUILD_TEST=ON \
                  -D CMAKE_CONFIGURATION_TYPES="Release;Debug" \
                  -D CMAKE_PREFIX_PATH="/usr/local/opt/ncurses;$(brew --prefix qt5)" \
                  -D Python3_EXECUTABLE:FILEPATH=/opt/local/bin/python3

        - name: build
          shell: bash
          run: |
              cmake --build build --config Debug   --target all
              cmake --build build --config Release --target all

        - name: install
          shell: bash
          run: |
              cmake --install build --config Release --prefix package

        - name: source package
          shell: bash
          run: |
              cmake --build build --config Release --target package_source

        - name: test
          shell: bash
          run: |
              cd build
              ctest --output-on-failure --build-config Debug
              ctest --output-on-failure --build-config Release
