name: Windows CI

on: [push]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                      name: "Windows 2019",
                      os: windows-2019,
                      cc: "cl", cxx: "cl",
                      environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
                  }
                - {
                      name: "Windows 2022",
                      os: windows-2022,
                      cc: "cl", cxx: "cl",
                      environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
                  }

        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.name }}

        timeout-minutes: 120

        steps:

        - name: Create build directory
          run: mkdir build
          shell: cmd

        - name: Checkout PCRaster
          uses: actions/checkout@v2

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: false
              python-version: 3.9
              channels: conda-forge
              mamba-version: "*"

        - name: Configure PCRaster
          shell: cmd
          run: |
              "mamba install numpy cmake ninja boost-cpp qt xerces-c libgdal psutil make" &&
              "${{ matrix.config.environment_script }}" &&
              cmake ^
                  -S . ^
                  -B build ^
                  -G"Ninja Multi-Config" ^
                  -D CMAKE_C_COMPILER=${{ matrix.config.cc }} ^
                  -D CMAKE_CXX_COMPILER=${{ matrix.config.cxx }} ^
                  -D PCRASTER_BUILD_TEST=ON ^
                  -D CMAKE_INSTALL_PREFIX=package

        - name: Build debug
          shell: cmd
          run: |
              cmake --build build --config Debug --target all

        - name: Build release
          shell: cmd
          run: |
              cmake --build build --config Release --target all

        - name: Install PCRaster
          shell: cmd
          run: |
              cmake --install build --config Release

        - name: Create source package
          shell: cmd
          run: |
              cmake --build build --config Release --target package_source

        - name: Test debug
          shell: cmd
          run: |
              ctest --test-dir build --output-on-failure --build-config Debug

        - name: Test release
          shell: cmd
          run: |
              ctest --test-dir build --output-on-failure --build-config Release
