name: Windows CI

on: [push]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-2019, windows-2022]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }}

        timeout-minutes: 120

        steps:

        - name: Checkout PCRaster
          uses: actions/checkout@v2

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: false
              python-version: 3.9
              channels: conda-forge
              mamba-version: "*"
        - shell: bash -l {0}
          run: |
              mamba install numpy cmake ninja boost-cpp qt xerces-c libgdal psutil make

        - name: Configure PCRaster
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build \
                  -G"Ninja Multi-Config" \
                  -D PCRASTER_BUILD_TEST=ON \
                  -D CMAKE_INSTALL_PREFIX=package

        - name: Build debug
          shell: bash
          run: |
              cmake --build build --config Debug --target all

        - name: Build release
          shell: bash
          run: |
              cmake --build build --config Release --target all

        - name: Install PCRaster
          shell: bash
          run: |
              cmake --install build --config Release

        - name: Create source package
          shell: bash
          run: |
              cmake --build build --config Release --target package_source

        - name: Test debug
          env:
          shell: bash
          run: |
              ctest --test-dir build --output-on-failure --build-config Debug

        - name: Test release
          env:
          shell: bash
          run: |
              ctest --test-dir build --output-on-failure --build-config Release
